NUM_GPUS: 1
NUM_SHARDS: 1
OUTPUT_DIR: ""
RUN_N_TIMES: 1
MODEL:
  TYPE: "vit"
  TRANSFER_TYPE: "dap"
  MODEL_ROOT: "./model"
  DAP:
    CURRENT_LAMBDA: 1.0
    SIM_LAMBDA: 0.1
    NUM_DAP_TOKENS: 10
    TASK_EMB: 16
SOLVER:
  BASE_LR: 0.01
  OPTIMIZER: 'adam'
  MOMENTUM: 0.9
  BETA1: 0.9
  BETA2: 0.9
  WEIGHT_DECAY: 0.0
  WARMUP_EPOCH: 0
  TOTAL_EPOCH: 30
  SCHEDULER: "linear"
  GRAD_CLIP: 1.
  GRAD_CLIP_APPLY: True
  PATIENCE: 300
  LOSS: "softmax"
  LOG_EVERY_N: 100
DATA:
  NAME: ""
  NUMBER_CLASSES: -1
  BATCH_SIZE: 128
  DATAPATH: "./dataset"
  FEATURE: "sup_vitb16_imagenet21k"
